/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multijar.app;

import multijar.constraint.MyConstraint;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello from App");

        String appTxt = MyConstraint.loadTxtFileContent("/datajar.txt");
        System.out.println(appTxt);
    }

    /*
    private static String loadTxtFileContent(String textFileName){
        String res = null;

        InputStream is = null;
        try{
            is = Class.forName("multijar.app.App").getResourceAsStream(textFileName);
            byte[] dat = is.readAllBytes();
            res = new String(dat, StandardCharsets.UTF_8);
        }
        catch (Exception e){
            throw new RuntimeException(e);
        }
        finally {
            if(is != null) {
                try {
                    is.close();
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        }
        return res;
    }

     */
}
